# les parametres globals pour toutes microservices
global:
  params:
    p1 : "valeur1 pour tous les microservices"
    p2 : "valeur2 pour tous les microservices"

# les parametres de connexion a la base de donnees
# les parametres de connexion au serveur de messagerie
# les parametres de connexion au serveur de stockage
# les parametres de connexion au serveur de cache
# les parametres de connexion au serveur de recherche
# les parametres de connexion au serveur de log
# les parametres de connexion au serveur de monitoring
# les parametres de connexion au serveur de configuration
# les parametres de connexion au serveur de securite
# les parametres de connexion au serveur de notification
# les parametres de connexion au serveur de gestion des utilisateurs
# les parametres de connexion au serveur de gestion des roles
# les parametres de connexion au serveur de gestion des permissions
# les parametres de connexion au serveur de gestion des sessions
# les parametres de connexion au serveur de gestion des tokens
# les parametres de connexion au serveur de gestion des evenements
# les parametres de connexion au serveur de gestion des transactions
# les parametres de connexion au serveur de gestion des requetes

