#test config params for inventory service
spring:
  datasource:
    url: jdbc:h2:mem:inventoryDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
managemet:
    endpoints:
        web:
        exposure:
            include: "*"

